### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by Cyruxx** [youngandcreative/platform-real-estate#2]
- [ ] Properties
- [ ] States
- [ ] Cities
- [ ] Areas
- [ ] Object types
- [ ] Equpment (Attributes) (e.g. pets allowed, parking lot) (Types: boolean)
- [ ] Status "sold", "available"
- [ ] Custom Fields ( use platform/attributes )

**Comment by Cyruxx** [comment]
**Properties:**
Title, Street, Housenumber, rooms, size_total, size_living, size_usable, rent_or_buy, price_per_month, price, additional_costs, courtage, available_at, rooms, rooms_sleeping, rooms_bath, floor, floors, description (markdown), position_lat, position_long

**Properties additionals:**
Users can add additional attributes, those will show up in an "additional" section

**Property types:**
Name, Description, slug

**States:**
Name, Country

**Cities:**
ZIP, Name, Country, slug

**Areas:**
CityId, Name, ZIP,

**Equipment_to_Properties:**
PropertyID, EquipmentID

**Equipment:**
Name

**Settings:**
Measuring units:
m²; f²

**Comment by Cyruxx** [comment]
Create a JavaScript enabled selection for areas to make a country -> state -> city -> area relationship.
